name: commenter
on: [pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.CT_GH_TOKEN }}
          message: Nice PR!ğŸ‘