name: Comment PR if files on folder change
on: 
    pull_request: 
        paths: 
        - 'lgothelipe/**'
jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - uses: mshick/add-pr-comment@v1
              with:
                  repo-token: ${{ secrets.LG_GITHUB_TOKEN }}
                  message: Nice PR!ğŸ‘
                  allow-repeats: false
